apiVersion: apps/v1
kind: Deployment
metadata:
  name: movies-python
  labels:
    app: movies-python
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movies-python
  template:
    metadata:
      name: movies-python
      labels:
        app: movies-python
    spec:
      shareProcessNamespace: true
      containers:
        - name: movies-python
          image: zhangyicloud/movies-python:latest
          imagePullPolicy: Always

        - name: datakit-profiler
          image: pubrepo.jiagouyun.com/dataflux/py-spy:0.1.0
          imagePullPolicy: IfNotPresent
          workingDir: /app/datakit-profiler
          env:
            - name: DK_AGENT_HOST # datakit listening host
              value: "192.168.209.128"
            - name: DK_AGENT_PORT # datakit listening port
              value: "9529"
            - name: DK_PROFILE_VERSION # user's app version
              value: "1.2.333"
            - name: DK_PROFILE_ENV # user's app run env
              value: "prod"
            - name: DK_PROFILE_DURATION # profiling duration at every time
              value: "240"
            - name: DK_PROFILE_SCHEDULE # profiling schedule plan
              value: "*/20 * * * *"
          command:
            - bash
            - "-c"
            - "./profiling.sh --add-crontab; cron -f"
          securityContext:
            capabilities:
              add:
                - SYS_PTRACE
          volumeMounts:
            - mountPath: /etc/localtime
              name: timezone
              readOnly: true
      restartPolicy: Always
      volumes:
        - name: timezone
          hostPath:
            path: /etc/localtime
            type: FileOrCreate